// Copyright 2017-2021 @reef-defi/dev authors & contributors
// SPDX-License-Identifier: Apache-2.0
// Auto-generated by @polkadot/dev, do not edit
export const packageInfo = {
  name: '@dust-defi/dev',
  version: '0.63.19'
};